server:
    port:9001
    
spring:
    application:
        name:trainer
        
    datasourse:
        driver-class-name: com.mysql.cj.jdbc.Driver
        uri: jdbc:mysql://localhost:3306/trinersdb?serverTimezone=UTC
        username: root
        password: 
        
    sql:
        innit:
            mode:always
            
    jps:
        hibernate:
            ddl-auto: update
        show-sql: true
        
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQL8Dialect
                